[project]
name = "radio-map-reconstruction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lzj", email = "2575634450@qq.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "pytest>=9.1.1",
    "pyyaml>=6.0.3",
    "swanlab>=0.9.7",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "tqdm>=4.66.5",
]

[project.scripts]
train = "radio_map_reconstruction.train:train"
train-sampler = "radio_map_reconstruction.sampler_train:train_sampler"
eval = "radio_map_reconstruction.eval:eval"
eval-sampler = "radio_map_reconstruction.sampler_eval:eval_sampler"
plot-results = "radio_map_reconstruction.plot:plot_results"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu132"
